spring:
  application:
    name: mixi-user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:ENC(wuxmSwTVsNPnvznsPQ9Da6aAZ9HVaSUjscJmUqSBszl5PF0J/6W6qn5bviPb3cEtq9gsmRQ9OXv7SkB3m/tNZEaqXvwGJN7Iu0pw01PILPurQyi6J8nYj3J6E4vQSlaZ)}
    username: ${MYSQL_USERNAME:ENC(+IMKJ8579CxFfvdSJkGtDVu9nen9zm8y)}
    password: ${MYSQL_PASSWORD:ENC(s46BLckvILKia876w8vukdzL/UCMD3/CqedOUStw55dOQLmjHpoeEQ==)}
  cloud:
    nacos:
      server-addr: ENC(/hmK8b3NLF5b2wa20x/9/M6fh6Ry+fDyP36hIjU1Gw5T2FvlYP0ZBg==)
      username: ENC(nF6dMgeUkKVZFapN4YBt7W7blo/wthUx)
      password: ENC(X9SY/CPDBR946egBuu8lXsXv/lHEWmE8R3lDYGE539I=)
      namespace: 32281a6b-5578-4c51-a2e7-1c65eba79860
      discovery:
        namespace: b21e6a4b-33d1-44c3-9b24-8a682c897292
      config:
        namespace: b21e6a4b-33d1-44c3-9b24-8a682c897292
  redis:
    host: ${REDIS_HOST:ENC(CYSeINCgW1v+0H0TIyGx2nj7cG6F8OG0sp9M481P9PY=)}
    port: 6379
    database: 10
    password: ${REDIS_PASSWORD:ENC(UfTTwtjZePaRqY8sq4P7hNYiPj/xIN6GPu9Z5TkOV0Q=)}

mixi:
  verifyLinkUrl: ${VERIFY_LINK:ENC(TSJqSXcliRzeuAglhUhXoXKKFZ5h2Xg22QdG6k2i/fAhQUOwGBpsEykeT/SJUTSYW8Xko2Kda+SIMa8O4u4XFQ==)}
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: genius_serve_0704
