/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/CreatRoom': RouteRecordInfo<'/CreatRoom', '/CreatRoom', Record<never, never>, Record<never, never>>,
    '/demo/chatDemo': RouteRecordInfo<'/demo/chatDemo', '/demo/chatDemo', Record<never, never>, Record<never, never>>,
    '/demo/Login': RouteRecordInfo<'/demo/Login', '/demo/Login', Record<never, never>, Record<never, never>>,
    '/demo/MainLayout': RouteRecordInfo<'/demo/MainLayout', '/demo/MainLayout', Record<never, never>, Record<never, never>>,
    '/demo/Room': RouteRecordInfo<'/demo/Room', '/demo/Room', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/LinkJoin': RouteRecordInfo<'/LinkJoin', '/LinkJoin', Record<never, never>, Record<never, never>>,
    '/LoginView': RouteRecordInfo<'/LoginView', '/LoginView', Record<never, never>, Record<never, never>>,
    '/Verify-email': RouteRecordInfo<'/Verify-email', '/Verify-email', Record<never, never>, Record<never, never>>,
  }
}
